### This notebook combines all the raw measured burst properties from different telescopes and measuring techniques and massages them in the final burst properties table as presented in the paper.

##### Some code is very hardcoded, but you will have to live with that.

In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm
from astropy import units as u
pd.set_option("display.max_rows", 80)

In [2]:
def bandwidth_calc(df, telescope, id):
    '''
    input: pandas dataframe where each line has the burst properties per component
    return the bandwith of a burst
    '''
    obs_band = df.f0_MHz.values[0]
    
    #Pband
    if obs_band == 328.0:
        bw_obs = 54
        
    #Lband
    elif obs_band:
        bw_obs = 128

    if telescope == 'st':
        bw_obs = 98

    if id == "B110-tr" or id == "B122-tr":
        bw_obs= 256
    #We take the absolute value, since the fwidth values can be negative
    #The bandwidth comes from autocorrelation and we define everything larger than FWHM as the BW
    signal_bw = int(abs(df.fwidth_sigma_MHz.values.max()) * 2.355)
    if signal_bw > bw_obs * 0.75:
        signal_bw = bw_obs

    return signal_bw, obs_band     

def toa_calulator(df):
    '''
    Return the toa of a burst
    in the case of multiple components of a single burst, take the middle of the burst
    '''
    if df.shape[0] == 1:
        mjd = df.iloc[0]["toa_bary_tdb_inf_freq"]

    elif df.shape[0] > 1:
        mjd_list = df["toa_bary_tdb_inf_freq"].values
        mjd = (mjd_list[0] + mjd_list[-1]) / 2
 
    return mjd

def toa_utc_calulator(df):
    '''
    Return the toa of a burst
    in the case of multiple components of a single burst, take the middle of the burst
    '''
    if df.shape[0] == 1:
        mjd = df.iloc[0]["toa_mjd_utc"]

    elif df.shape[0] > 1:
        mjd_list = df["toa_mjd_utc"].values
        mjd = (mjd_list[0] + mjd_list[-1]) / 2
 
    return mjd
    
def peak_sn_calc(df):
    '''
    input: pandas dataframe where each line has the burst properties per component
    Return the maximum value of the snr of all comp
    '''
    num_comp = df.shape[0]
    if num_comp == 0:
        print(f"WRONG WRONG : {df}")
    if num_comp == 1:
        peak_sn = df.iloc[0]["peak_snr"]
    elif num_comp > 1:
        peak_list = df["peak_snr"].values
        peak_sn = np.max(peak_list)
    
    return peak_sn,num_comp

def peak_sn_calc(df):
    '''
    input: pandas dataframe where each line has the burst properties per component
    Return the maximum value of the snr of all comp
    '''
    num_comp = df.shape[0]
    if num_comp == 0:
        print(f"WRONG WRONG : {df}")
    if num_comp == 1:
        peak_sn = df.iloc[0]["peak_snr"]
    elif num_comp > 1:
        peak_list = df["peak_snr"].values
        peak_sn = np.max(peak_list)
    
    return peak_sn,num_comp

def isotropic_energies(fluences, distance=616):
    "Convert list of fluences to spectral densities"
    "Method based on fluence.py by K.Nimmo"

    #convert from jyms to jys
    fluence_jys = np.array(fluences) * 1e-3

    dis = 1.0 * u.megaparsec
    megap_cm = dis.to(u.cm).value

    #mpc to cm
    distance_lum_cm = megap_cm*distance

    #redshift correction, see evernote for details
    #redshift is from: Snelders et al
    #distance is also from Ravi et al, FAST converts themselves based on PLANCK 2016
    #link: https://ui.adsabs.harvard.edu/abs/2025ApJ...992L..35B/abstract
    z = 0.130287
    red_cor = 1 / (1 + z)**2

    energy_iso = fluence_jys * 4*np.pi*(distance_lum_cm**2) * 1e-23 * red_cor
    #print(energy_iso)

    return energy_iso

def speclum(fluence, ontime, distance=616, z=0.130287):
    '''
    fluence assumed in Jy~ms
    ontime assumed in ms
    distance assumed in Mpc
    '''
    # actual ontime or total width? Width gives a lover limit on the luminosity.
    
    #convert Jy ms to J s; and ms to s
    fluence_jys = fluence*1e-3
    ontime /= 1e3
    
    #convert Mpc to cm
    distance_lum_cm = 3.086e24*distance
    energy_iso= fluence_jys*4*np.pi*(distance_lum_cm**2)*1e-23 / (1+z)**(2)
    lum_spec = energy_iso/ontime
    
    return lum_spec

In [3]:
def fluence_looper(df_fluence, two_bit_flag=False):
    """
    function to sum over the fluences components of bursts
    
    Input: The burst_csv file with all information, spc/sfxc/scale
    This is needed because we return a df with fluence (spc) and toa (sfxc)
    
    return: pandas dataframe with: id/fluence/telescope/c_freq/toa/width_ms
    """

    #the burst names to loop over
    exps = df_fluence['id'].unique()

    #Create a list with the telescope names for easy filtering later on
    exps_tel = [i.split('-')[1] for i in exps]

    #loop over every burst to sum the fluence
    info_list = []
    for exp, telescope in zip(exps, exps_tel):
        
        #Fluence: Making a small temp df for each exp, only taking the spc values
        if telescope != 'st' and two_bit_flag == False:

            ## This coding line reads like garbage - but deal with it because it works
            if exp == "B125-o8" or exp == "B157-tr":
                fluence_df_exp_temp = df_fluence[df_fluence['id'] == exp]
            
                #TOA
                toa = toa_calulator(fluence_df_exp_temp) 
                toa_utc = toa_utc_calulator(fluence_df_exp_temp) 
                
            else:
                fluence_df_exp_temp = df_fluence[(df_fluence['id'] == exp) & (df_fluence['src'] == 'spc')]
                
                #TOA
                fluence_df_exp_temp_mjd = df_fluence[(df_fluence['id'] == exp) & (df_fluence['src'] == 'sfxc')]
                toa = toa_calulator(fluence_df_exp_temp_mjd) 
                toa_utc = toa_utc_calulator(fluence_df_exp_temp_mjd)
                
        elif telescope == 'st' or two_bit_flag==True:
            fluence_df_exp_temp = df_fluence[df_fluence['id'] == exp]
            
            #TOA
            toa = toa_calulator(fluence_df_exp_temp) 
            toa_utc = toa_utc_calulator(fluence_df_exp_temp) 

        #Calculate the total fluence
        fluence = sum(fluence_df_exp_temp['fluence_jyms'].values)

        #Calculate isotropic energies
        energies_isotropic = isotropic_energies(fluence)
        
        #Calculate the max SN of a burst
        peak_sn, num_comp = peak_sn_calc(fluence_df_exp_temp)
    
        #Calculate the bandwith
        signal_bw, cent_freq = bandwidth_calc(fluence_df_exp_temp, telescope, id=exp)
        
        #width in ms
        width_t = fluence_df_exp_temp.end_acf_range.values.max() - fluence_df_exp_temp.begin_acf_range.values.min()

        #Calculate the spectral luminosity
        spel_lum = speclum(fluence, width_t, distance=616, z=0.130287)
        
        #Since the F0 is the same for all components, take all components, take the first entry
        cent_freq = fluence_df_exp_temp['f0_MHz'].values[0]
        
        #Add to the list
        info_list.append([toa, peak_sn, fluence, num_comp, width_t, energies_isotropic, spel_lum, \
                          signal_bw, cent_freq, two_bit_flag, toa_utc])                          
        
    #Convert the fluence list to array
    info_list_arr = np.asarray(info_list)
    
    #Convert the info to dataframe
    new_data = {'id': exps, 'station': exps_tel, 'toa': info_list_arr[:,0], \
                'peak_sn': info_list_arr[:,1], 'fluence': info_list_arr[:,2], \
                'width_ms': info_list_arr[:,4], \
                'bandwidth': info_list_arr[:,7], \
                'central frequency': info_list_arr[:,8], \
                'spectral-density': info_list_arr[:,5],\
                'spectral-luminosity': info_list_arr[:,6], \
                '2bit-wb-tag': info_list_arr[:,9],
                'toa_utc': info_list_arr[:,10]}
    
    df_new_fluence = pd.DataFrame(data=new_data)

    #add only the index number as a seperate column for potential later use
    df_new_fluence['burst-index'] = df_new_fluence['id'].str.split('-').str[0].str[1:].astype(int)
    
    return df_new_fluence

In [4]:
def df_to_small_table(file):
    """
    Function to load in the burst.csv file and return the shortend version of the .csv file
    """

    #load in the main csv file
    fluence_df = pd.read_csv(file, index_col=0, header=0, na_values='NA', engine='python').reset_index(drop=True)
    fluence_df.sort_values(by=['id'])

    if file == "2bit_westerbork_bursts_r147.csv":
        two_bit_flag = True
    else:
        two_bit_flag = False

    #B86-88-tr were to faint to quantify burst properties
    fluence_df = fluence_df[~fluence_df['id'].isin(['B86-tr', 'B88-tr'])]
    
    df_combined = fluence_looper(fluence_df, two_bit_flag)    
    df_combined.sort_values(by=['id'])

    return df_combined

def df_formatter(df_combined):
    
    #Resort and reset the df
    df_combined = df_combined.sort_values(by=['toa'])
    df_combined = df_combined.reset_index(drop=True)
    
    #Setting the formatting of the numbers correct
    df_combined["bandwidth"] = df_combined["bandwidth"].astype(int)
    df_combined["central frequency"] = df_combined["central frequency"].astype(int)
    
    df_combined['fluence_err'] = pd.to_numeric(df_combined['fluence'] * 0.2, errors='coerce').round(2)
    
    # #Minimum spectral energy is on the order of 1e30 // calculated with the .min()
    df_combined['spectral-density'] /= 1e30
    df_combined['spec_den_err'] = df_combined['spectral-density'] * 0.2
    df_combined['spectral-density'] = df_combined['spectral-density'].round(2)
    df_combined['spec_den_err'] = df_combined['spec_den_err'].round(2)
    
    # #Minimum spectral lum is on the order of 1e31 // calculated with the .min()
    df_combined['spectral-luminosity'] /= 1e32
    df_combined['spec_lum_err'] = df_combined['spectral-luminosity'] * 0.2
    df_combined['spectral-luminosity'] = df_combined['spectral-luminosity'].round(2)
    df_combined['spec_lum_err'] = df_combined['spec_lum_err'].round(2)

    df_combined['peak_sn'] = pd.to_numeric(df_combined['peak_sn'], errors='coerce').round(2)
    df_combined['width_ms'] = pd.to_numeric(df_combined['width_ms'], errors='coerce').round(2)
    df_combined['fluence'] = pd.to_numeric(df_combined['fluence'], errors='coerce').round(2)
    
    df_combined['peak_sn'] = df_combined['peak_sn'].round(2)
    df_combined['width_ms'] = df_combined['width_ms'].round(2)
    df_combined['fluence'] = df_combined['fluence'].round(2)

    df_combined["2bit-wb-tag"] = df_combined["2bit-wb-tag"].astype(int)
    
    df_paper = df_combined[['id', 'station', 'toa', 'toa_utc', 'peak_sn', 'fluence', 'fluence_err',\
                            'width_ms', 'spectral-density', 'spec_den_err', 'spectral-luminosity', 'spec_lum_err',\
                            'bandwidth', 'central frequency', '2bit-wb-tag']]

    new_rows = pd.DataFrame([
    {
        "id": "B48-wb",
        "station": "wb",
    },
    {
        "id": "B81-o8",
        "station": "o8",
    },
    {
        "id": "B86-tr",
        "station": "tr",
    },
    {
        "id": "B88-tr",
        "station": "tr",
    }
    ])
    df_paper = pd.concat([df_paper, new_rows], ignore_index=True)

    df_combined = df_combined.sort_values(by=['toa'])

    return df_paper

In [5]:
def df_combiner():

    df_westerbork_2bit = df_to_small_table(file="2bit_westerbork_bursts_r147.csv")
    df_stockert = df_to_small_table(file="stockert_bursts_r147.csv")
    df_westerbork_pband = df_to_small_table(file="westerbork_pband.csv")
    df_onsala = df_to_small_table(file="hyperflash_onsala_L.csv")
    df_torun = df_to_small_table(file="hyperflash_torun_L.csv")
    df_westerbork = df_to_small_table(file="hyperflash_westerbork_L.csv")
    
    dfs = [
        df_westerbork_2bit,
        df_stockert,
        df_westerbork_pband,
        df_onsala,
        df_torun,
        df_westerbork,
    ]
    
    df_all = pd.concat(dfs, ignore_index=True)
    df_all = df_all.sort_values(by=['toa'])
    #display(df_all)

    df_paper = df_formatter(df_all)
    display(df_paper)

    name_csv = "FRB20240114A_HyperFlash_paper_table_v2.csv"
    df_paper.to_csv(name_csv, header=True, index=True, na_rep='NA')
    
    return df_paper
    
df_paper = df_combiner()

,id,station,toa,toa_utc,peak_sn,fluence,fluence_err,width_ms,spectral-density,spec_den_err,spectral-luminosity,spec_lum_err,bandwidth,central frequency,2bit-wb-tag
0,B01-wb,wb,60341.533745,60341.538213,8.08,203.23,40.65,45.06,72.22,14.44,16.03,3.21,40.0,328.0,0.0
1,B02-wb,wb,60355.639527,60355.644167,5.26,16.66,3.33,14.34,5.92,1.18,4.13,0.83,128.0,1271.0,0.0
2,B03-st,st,60357.339134,60357.343782,8.60,20.15,4.03,3.71,7.16,1.43,19.28,3.86,98.0,1381.0,0.0
3,B04-st,st,60357.433876,60357.438523,6.00,25.10,5.02,9.61,8.92,1.78,9.28,1.86,53.0,1381.0,0.0
4,B05-st,st,60361.542887,60361.547509,5.21,35.49,7.10,7.86,12.61,2.52,16.04,3.21,98.0,1381.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,B180-tr,tr,60819.332590,60819.331089,7.58,7.22,1.44,7.17,2.57,0.51,3.58,0.72,95.0,1444.0,0.0
212,B48-wb,wb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
213,B81-o8,o8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214,B86-tr,tr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,B88-tr,tr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_2bit = df_paper[df_paper["2bit-wb-tag"] == 1.0]
df_2bit = df_2bit.sort_values(by=['fluence'])
display(df_2bit)
print(len(df_2bit.index))

,id,station,toa,toa_utc,peak_sn,fluence,fluence_err,width_ms,spectral-density,spec_den_err,spectral-luminosity,spec_lum_err,bandwidth,central frequency,2bit-wb-tag
203,B172-wb,wb,60807.267393,60807.267029,5.43,10.85,2.17,10.24,3.86,0.77,3.77,0.75,71.0,1271.0,1.0
16,B17-wb,wb,60373.253667,60373.258074,6.47,11.49,2.30,4.10,4.08,0.82,9.97,1.99,128.0,1271.0,1.0
52,B52-wb,wb,60379.265983,60379.270192,5.37,12.10,2.42,6.14,4.30,0.86,7.00,1.40,128.0,1271.0,1.0
190,B161-wb,wb,60696.570776,60696.574916,4.65,13.77,2.75,11.26,4.89,0.98,4.35,0.87,128.0,1271.0,1.0
31,B31-wb,wb,60375.426785,60375.431127,6.75,16.15,3.23,13.31,5.74,1.15,4.31,0.86,128.0,1271.0,1.0
9,B10-wb,wb,60370.262306,60370.266790,5.10,16.21,3.24,11.26,5.76,1.15,5.11,1.02,128.0,1271.0,1.0
178,B150-wb,wb,60682.494586,60682.498021,6.36,17.23,3.45,10.24,6.12,1.22,5.98,1.20,128.0,1271.0,1.0
26,B27-wb,wb,60375.380475,60375.384819,6.38,17.39,3.48,7.17,6.18,1.24,8.63,1.73,128.0,1271.0,1.0
6,B07-wb,wb,60369.290731,60369.295237,5.47,17.45,3.49,4.86,6.20,1.24,12.75,2.55,128.0,1271.0,1.0
201,B170-wb,wb,60805.359486,60805.359298,15.12,17.65,3.53,2.82,6.27,1.25,22.28,4.46,96.0,1271.0,1.0
47,B46-wb,wb,60378.509319,60378.513556,6.42,19.62,3.92,13.31,6.97,1.39,5.24,1.05,128.0,1271.0,1.0
209,B179-wb,wb,60817.072561,60817.071283,8.03,21.07,4.21,12.29,7.49,1.50,6.09,1.22,128.0,1271.0,1.0
202,B171-wb,wb,60806.328032,60806.327755,9.81,23.24,4.65,4.61,8.26,1.65,17.92,3.58,128.0,1271.0,1.0
155,B129-wb,wb,60436.095512,60436.095710,4.68,25.15,5.03,37.89,8.94,1.79,2.36,0.47,128.0,1271.0,1.0
48,B47-wb,wb,60378.552629,60378.556864,5.04,25.16,5.03,11.26,8.94,1.79,7.94,1.59,128.0,1271.0,1.0
188,B159-wb,wb,60693.570551,60693.574565,7.67,25.16,5.03,4.10,8.94,1.79,21.83,4.37,128.0,1271.0,1.0
206,B175-wb,wb,60814.157155,60814.156148,9.01,27.84,5.57,12.29,9.90,1.98,8.05,1.61,128.0,1271.0,1.0
210,B178-wb,wb,60817.072561,60817.071283,7.89,28.74,5.75,16.38,10.21,2.04,6.24,1.25,128.0,1271.0,1.0
159,B133-wb,wb,60506.106183,60506.100738,6.07,67.80,13.56,18.94,24.09,4.82,12.72,2.54,128.0,1271.0,1.0
158,B132-wb,wb,60471.116486,60471.113486,9.26,77.12,15.42,26.62,27.41,5.48,10.30,2.06,94.0,1271.0,1.0

20

In [14]:
df_wb_non2bit = df_paper[df_paper["station"] == "wb"]
df_wb_non2bit = df_wb_non2bit.sort_values(by=['fluence'])
display(df_wb_non2bit)
print(len(df_wb_non2bit.index))

,id,station,toa,toa_utc,peak_sn,fluence,fluence_err,width_ms,spectral-density,spec_den_err,spectral-luminosity,spec_lum_err,bandwidth,central frequency,2bit-wb-tag
146,B123-wb,wb,60424.432518,60424.433747,5.44,6.09,1.22,3.07,2.16,0.43,7.05,1.41,78.0,1271.0,0.0
8,B09-wb,wb,60369.366278,60369.370769,4.43,7.34,1.47,22.53,2.61,0.52,1.16,0.23,77.0,1271.0,0.0
10,B11-wb,wb,60370.289589,60370.294059,4.85,8.67,1.73,11.26,3.08,0.62,2.74,0.55,128.0,1271.0,0.0
184,B156-wb,wb,60683.682305,60683.685796,4.94,9.48,1.90,3.58,3.37,0.67,9.40,1.88,128.0,1271.0,0.0
133,B110-wb,wb,60387.363333,60387.367176,5.88,10.14,2.03,2.56,3.61,0.72,14.09,2.82,128.0,1271.0,0.0
33,B32-wb,wb,60375.444173,60375.448500,4.54,10.33,2.07,12.29,3.67,0.73,2.99,0.60,128.0,1271.0,0.0
203,B172-wb,wb,60807.267393,60807.267029,5.43,10.85,2.17,10.24,3.86,0.77,3.77,0.75,71.0,1271.0,1.0
13,B14-wb,wb,60370.453285,60370.457751,6.20,11.13,2.23,3.33,3.95,0.79,11.88,2.38,128.0,1271.0,0.0
16,B17-wb,wb,60373.253667,60373.258074,6.47,11.49,2.30,4.10,4.08,0.82,9.97,1.99,128.0,1271.0,1.0
52,B52-wb,wb,60379.265983,60379.270192,5.37,12.10,2.42,6.14,4.30,0.86,7.00,1.40,128.0,1271.0,1.0
204,B173-wb,wb,60809.319875,60809.319305,4.21,13.55,2.71,7.68,4.82,0.96,6.27,1.25,128.0,1271.0,0.0
156,B130-wb,wb,60453.093491,60453.092095,9.49,13.67,2.73,3.07,4.86,0.97,15.82,3.16,128.0,1271.0,0.0
190,B161-wb,wb,60696.570776,60696.574916,4.65,13.77,2.75,11.26,4.89,0.98,4.35,0.87,128.0,1271.0,1.0
189,B160-wb,wb,60696.409105,60696.413225,9.89,14.02,2.80,5.63,4.98,1.00,8.85,1.77,128.0,1271.0,0.0
17,B18-wb,wb,60373.284092,60373.288484,6.34,15.40,3.08,7.17,5.47,1.09,7.63,1.53,128.0,1271.0,0.0
11,B12-wb,wb,60370.416514,60370.420980,6.97,15.48,3.10,7.17,5.50,1.10,7.67,1.53,128.0,1271.0,0.0
31,B31-wb,wb,60375.426785,60375.431127,6.75,16.15,3.23,13.31,5.74,1.15,4.31,0.86,128.0,1271.0,1.0
9,B10-wb,wb,60370.262306,60370.266790,5.10,16.21,3.24,11.26,5.76,1.15,5.11,1.02,128.0,1271.0,1.0
1,B02-wb,wb,60355.639527,60355.644167,5.26,16.66,3.33,14.34,5.92,1.18,4.13,0.83,128.0,1271.0,0.0
34,B33-wb,wb,60375.447941,60375.452268,5.24,17.17,3.43,15.36,6.10,1.22,3.97,0.79,25.0,1228.0,0.0
178,B150-wb,wb,60682.494586,60682.498021,6.36,17.23,3.45,10.24,6.12,1.22,5.98,1.20,128.0,1271.0,1.0
26,B27-wb,wb,60375.380475,60375.384819,6.38,17.39,3.48,7.17,6.18,1.24,8.63,1.73,128.0,1271.0,1.0
6,B07-wb,wb,60369.290731,60369.295237,5.47,17.45,3.49,4.86,6.20,1.24,12.75,2.55,128.0,1271.0,1.0
201,B170-wb,wb,60805.359486,60805.359298,15.12,17.65,3.53,2.82,6.27,1.25,22.28,4.46,96.0,1271.0,1.0
47,B46-wb,wb,60378.509319,60378.513556,6.42,19.62,3.92,13.31,6.97,1.39,5.24,1.05,128.0,1271.0,1.0
209,B179-wb,wb,60817.072561,60817.071283,8.03,21.07,4.21,12.29,7.49,1.50,6.09,1.22,128.0,1271.0,1.0
187,B158-wb,wb,60686.616987,60686.620643,12.48,21.13,4.23,1.79,7.51,1.50,41.92,8.38,128.0,1271.0,0.0
24,B25-wb,wb,60375.347630,60375.351960,6.21,21.19,4.24,12.29,7.53,1.51,6.13,1.23,128.0,1271.0,0.0
152,B127-wb,wb,60433.203153,60433.203602,4.14,21.31,4.26,10.75,7.57,1.51,7.05,1.41,94.0,1271.0,0.0
18,B19-wb,wb,60373.352482,60373.356872,7.78,22.15,4.43,7.68,7.87,1.57,10.25,2.05,128.0,1271.0,0.0
202,B171-wb,wb,60806.328032,60806.327755,9.81,23.24,4.65,4.61,8.26,1.65,17.92,3.58,128.0,1271.0,1.0
134,B112-wb,wb,60387.529496,60387.533331,5.73,23.71,4.74,4.86,8.43,1.69,17.32,3.46,128.0,1271.0,0.0
208,B177-wb,wb,60816.333009,60816.331785,4.82,23.81,4.76,10.75,8.46,1.69,7.87,1.57,128.0,1271.0,0.0
155,B129-wb,wb,60436.095512,60436.095710,4.68,25.15,5.03,37.89,8.94,1.79,2.36,0.47,128.0,1271.0,1.0
188,B159-wb,wb,60693.570551,60693.574565,7.67,25.16,5.03,4.10,8.94,1.79,21.83,4.37,128.0,1271.0,1.0
48,B47-wb,wb,60378.552629,60378.556864,5.04,25.16,5.03,11.26,8.94,1.79,7.94,1.59,128.0,1271.0,1.0
25,B26-wb,wb,60375.378553,60375.382882,4.78,26.11,5.22,16.38,9.28,1.86,5.66,1.13,128.0,1271.0,0.0
206,B175-wb,wb,60814.157155,60814.156148,9.01,27.84,5.57,12.29,9.90,1.98,8.05,1.61,128.0,1271.0,1.0
173,B145-wb,wb,60679.707817,60679.711065,9.05,27.96,5.59,10.24,9.94,1.99,9.71,1.94,70.0,1271.0,0.0
172,B144-wb,wb,60679.669002,60679.672247,8.60,28.05,5.61,10.75,9.97,1.99,9.27,1.85,83.0,1271.0,0.0
210,B178-wb,wb,60817.072561,60817.071283,7.89,28.74,5.75,16.38,10.21,2.04,6.24,1.25,128.0,1271.0,1.0
170,B142-wb,wb,60679.587260,60679.590501,5.70,30.91,6.18,10.24,10.98,2.20,10.73,2.15,128.0,1271.0,0.0
27,B28-wb,wb,60375.396560,60375.400889,8.26,31.05,6.21,19.46,11.04,2.21,5.67,1.13,95.0,1271.0,0.0
28,B29-wb,wb,60375.400515,60375.404844,8.84,32.37,6.47,11.26,11.50,2.30,10.21,2.04,74.0,1271.0,0.0
174,B146-wb,wb,60679.711400,60679.714648,17.43,34.68,6.94,6.66,12.32,2.46,18.52,3.70,91.0,1271.0,0.0
151,B126-wb,wb,60432.385082,60432.385605,8.14,36.38,7.28,10.75,12.93,2.59,12.03,2.41,128.0,1271.0,0.0
179,B151-wb,wb,60682.736612,60682.740047,4.93,41.12,8.22,20.99,14.61,2.92,6.96,1.39,128.0,1271.0,0.0
193,B163-wb,wb,60698.534229,60698.538431,6.74,41.33,8.27,14.85,14.69,2.94,9.89,1.98,128.0,1271.0,0.0
30,B30-wb,wb,60375.424961,60375.429289,5.74,42.07,8.41,12.29,14.95,2.99,12.17,2.43,73.0,1271.0,0.0
12,B13-wb,wb,60370.447553,60370.452019,12.83,42.40,8.48,5.63,15.07,3.01,26.76,5.35,93.0,1271.0,0.0
175,B147-wb,wb,60679.742649,60679.745899,6.67,61.37,12.27,17.41,21.81,4.36,12.53,2.51,128.0,1271.0,0.0
159,B133-wb,wb,60506.106183,60506.100738,6.07,67.80,13.56,18.94,24.09,4.82,12.72,2.54,128.0,1271.0,1.0
161,B135-wb,wb,60573.926431,60573.920993,21.37,70.25,14.05,5.50,24.96,4.99,45.37,9.07,82.0,1271.0,0.0
158,B132-wb,wb,60471.116486,60471.113486,9.26,77.12,15.42,26.62,27.41,5.48,10.30,2.06,94.0,1271.0,1.0
171,B143-wb,wb,60679.633583,60679.636826,9.62,92.09,18.42,26.11,32.73,6.55,12.54,2.51,128.0,1271.0,0.0
167,B139-wb,wb,60658.718969,60658.720640,34.06,118.20,23.64,3.20,42.01,8.40,131.30,26.26,24.0,1315.0,0.0
168,B140-wb,wb,60673.607068,60673.609905,33.00,173.43,34.69,11.52,61.63,12.33,53.51,10.70,128.0,1271.0,0.0
0,B01-wb,wb,60341.533745,60341.538213,8.08,203.23,40.65,45.06,72.22,14.44,16.03,3.21,40.0,328.0,0.0
162,B136-wb,wb,60581.877497,60581.872510,31.16,211.15,42.23,14.21,75.04,15.01,52.83,10.57,83.0,1271.0,0.0
126,B105-wb,wb,60386.372891,60386.376783,37.09,1435.53,287.11,36.86,510.16,102.03,138.42,27.68,54.0,328.0,0.0
164,B137-wb,wb,60586.957656,60586.952999,397.87,3982.85,796.57,31.49,1415.43,283.09,449.61,89.92,128.0,1271.0,0.0
212,B48-wb,wb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

62

In [20]:
df_paper_table = pd.concat([df_paper.head(6), df_paper.tail(10)])
display(df_paper_table)

,id,station,toa,toa_utc,peak_sn,fluence,fluence_err,width_ms,spectral-density,spec_den_err,spectral-luminosity,spec_lum_err,bandwidth,central frequency,2bit-wb-tag
0,B01-wb,wb,60341.533745,60341.538213,8.08,203.23,40.65,45.06,72.22,14.44,16.03,3.21,40.0,328.0,0.0
1,B02-wb,wb,60355.639527,60355.644167,5.26,16.66,3.33,14.34,5.92,1.18,4.13,0.83,128.0,1271.0,0.0
2,B03-st,st,60357.339134,60357.343782,8.60,20.15,4.03,3.71,7.16,1.43,19.28,3.86,98.0,1381.0,0.0
3,B04-st,st,60357.433876,60357.438523,6.00,25.10,5.02,9.61,8.92,1.78,9.28,1.86,53.0,1381.0,0.0
4,B05-st,st,60361.542887,60361.547509,5.21,35.49,7.10,7.86,12.61,2.52,16.04,3.21,98.0,1381.0,0.0
5,B06-st,st,60366.341592,60366.346149,5.26,16.72,3.34,3.50,5.94,1.19,17.00,3.40,98.0,1381.0,0.0
206,B175-wb,wb,60814.157155,60814.156148,9.01,27.84,5.57,12.29,9.90,1.98,8.05,1.61,128.0,1271.0,1.0
207,B176-tr,tr,60816.177709,60816.176500,4.85,7.27,1.45,7.17,2.58,0.52,3.61,0.72,128.0,1444.0,0.0
208,B177-wb,wb,60816.333009,60816.331785,4.82,23.81,4.76,10.75,8.46,1.69,7.87,1.57,128.0,1271.0,0.0
209,B179-wb,wb,60817.072561,60817.071283,8.03,21.07,4.21,12.29,7.49,1.50,6.09,1.22,128.0,1271.0,1.0
210,B178-wb,wb,60817.072561,60817.071283,7.89,28.74,5.75,16.38,10.21,2.04,6.24,1.25,128.0,1271.0,1.0
211,B180-tr,tr,60819.332590,60819.331089,7.58,7.22,1.44,7.17,2.57,0.51,3.58,0.72,95.0,1444.0,0.0
212,B48-wb,wb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
213,B81-o8,o8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214,B86-tr,tr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,B88-tr,tr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
print(df_paper['id'].values)

['B01-wb' 'B02-wb' 'B03-st' 'B04-st' 'B05-st' 'B06-st' 'B07-wb' 'B08-st'
 'B09-wb' 'B10-wb' 'B11-wb' 'B12-wb' 'B13-wb' 'B14-wb' 'B15-st' 'B16-st'
 'B17-wb' 'B18-wb' 'B19-wb' 'B20-st' 'B21-st' 'B22-st' 'B23-st' 'B24-st'
 'B25-wb' 'B26-wb' 'B27-wb' 'B28-wb' 'B29-wb' 'B30-st' 'B30-wb' 'B31-wb'
 'B31-st' 'B32-wb' 'B33-wb' 'B34-st' 'B35-st' 'B36-st' 'B37-st' 'B38-st'
 'B39-st' 'B40-st' 'B41-st' 'B42-st' 'B43-st' 'B44-st' 'B45-st' 'B46-wb'
 'B47-wb' 'B49-st' 'B50-st' 'B51-st' 'B52-wb' 'B53-st' 'B54-st' 'B55-st'
 'B56-st' 'B56-o8' 'B57-st' 'B57-o8' 'B58-st' 'B58-tr' 'B59-st' 'B60-st'
 'B60-tr' 'B61-st' 'B61-tr' 'B62-st' 'B63-o8' 'B64-tr' 'B65-o8' 'B65-tr'
 'B66-st' 'B67-o8' 'B66-tr' 'B68-o8' 'B68-tr' 'B70-o8' 'B71-o8' 'B72-o8'
 'B73-st' 'B73-o8' 'B74-st' 'B74-o8' 'B75-st' 'B75-o8' 'B76-st' 'B76-o8'
 'B77-o8' 'B78-o8' 'B79-o8' 'B80-st' 'B80-o8' 'B82-o8' 'B83-o8' 'B84-o8'
 'B85-o8' 'B85-tr' 'B86-o8' 'B87-st' 'B87-o8' 'B87-tr' 'B88-st' 'B88-o8'
 'B89-o8' 'B90-o8' 'B90-tr' 'B91-o8' 'B92-o8' 'B93-o8' 'B94-o8' 'B95-o8'
 'B96-o8' 'B97-o8' 'B98-o8' 'B99-o8' 'B100-st' 'B100-o8' 'B101-st'
 'B101-o8' 'B102-st' 'B102-o8' 'B103-st' 'B103-o8' 'B104-st' 'B104-o8'
 'B105-wb' 'B106-o8' 'B107-st' 'B107-o8' 'B108-o8' 'B109-st' 'B110-tr'
 'B110-wb' 'B112-wb' 'B113-st' 'B114-st' 'B115-st' 'B116-st' 'B117-st'
 'B118-st' 'B119-st' 'B120-st' 'B120-o8' 'B121-st' 'B122-tr' 'B123-wb'
 'B123-st' 'B124-st' 'B125-o8' 'B125-st' 'B126-wb' 'B127-wb' 'B127-st'
 'B128-o8' 'B129-wb' 'B130-wb' 'B131-st' 'B132-wb' 'B133-wb' 'B134-tr'
 'B135-wb' 'B136-wb' 'B137-tr' 'B137-wb' 'B138-tr' 'B139-tr' 'B139-wb'
 'B140-wb' 'B141-tr' 'B142-wb' 'B143-wb' 'B144-wb' 'B145-wb' 'B146-wb'
 'B147-wb' 'B148-tr' 'B149-tr' 'B150-wb' 'B151-wb' 'B152-tr' 'B153-tr'
 'B154-tr' 'B155-tr' 'B156-wb' 'B157-tr' 'B158-tr' 'B158-wb' 'B159-wb'
 'B160-wb' 'B161-wb' 'B162-o8' 'B163-tr' 'B163-wb' 'B164-tr' 'B165-tr'
 'B166-tr' 'B167-tr' 'B167-st' 'B168-tr' 'B169-tr' 'B170-wb' 'B171-wb'
 'B172-wb' 'B173-wb' 'B174-tr' 'B175-wb' 'B176-tr' 'B177-wb' 'B179-wb'
 'B178-wb' 'B180-tr' 'B48-wb' 'B81-o8' 'B86-tr' 'B88-tr']